/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiScanRouteImport } from './routes/api/scan'
import { Route as ApiScanLocateRouteImport } from './routes/api/scan.locate'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScanRoute = ApiScanRouteImport.update({
  id: '/api/scan',
  path: '/api/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScanLocateRoute = ApiScanLocateRouteImport.update({
  id: '/locate',
  path: '/locate',
  getParentRoute: () => ApiScanRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/api/scan': typeof ApiScanRouteWithChildren
  '/api/scan/locate': typeof ApiScanLocateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/api/scan': typeof ApiScanRouteWithChildren
  '/api/scan/locate': typeof ApiScanLocateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/api/scan': typeof ApiScanRouteWithChildren
  '/api/scan/locate': typeof ApiScanLocateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/privacy'
    | '/terms'
    | '/api/scan'
    | '/api/scan/locate'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/privacy'
    | '/terms'
    | '/api/scan'
    | '/api/scan/locate'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/privacy'
    | '/terms'
    | '/api/scan'
    | '/api/scan/locate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  ApiScanRoute: typeof ApiScanRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scan': {
      id: '/api/scan'
      path: '/api/scan'
      fullPath: '/api/scan'
      preLoaderRoute: typeof ApiScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scan/locate': {
      id: '/api/scan/locate'
      path: '/locate'
      fullPath: '/api/scan/locate'
      preLoaderRoute: typeof ApiScanLocateRouteImport
      parentRoute: typeof ApiScanRoute
    }
  }
}

interface ApiScanRouteChildren {
  ApiScanLocateRoute: typeof ApiScanLocateRoute
}

const ApiScanRouteChildren: ApiScanRouteChildren = {
  ApiScanLocateRoute: ApiScanLocateRoute,
}

const ApiScanRouteWithChildren =
  ApiScanRoute._addFileChildren(ApiScanRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  ApiScanRoute: ApiScanRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
