ALTER TABLE public.scans
  ADD COLUMN IF NOT EXISTS place_id TEXT,
  ADD COLUMN IF NOT EXISTS place_address TEXT,
  ADD COLUMN IF NOT EXISTS place_lat NUMERIC,
  ADD COLUMN IF NOT EXISTS place_lng NUMERIC;